### ISSUE TITLE
Broken in Firefox and Safari

### ISSUE THREAD

**Issue by edwardofclt** [swiftype/slack-hawk-down#14]
Not sure what the problem is - or where the error is arising from.

```
SyntaxError: invalid regexp group

XRegExp
src/github.com/redventures/gkw/web/node_modules/slack-hawk-down/dist/bundle.js:5195

  5192 |   }
  5193 | 
  5194 |   var generated = patternCache[pattern][flags];
> 5195 |   return augment(new RegExp(generated.pattern, generated.flags), generated.captures, pattern, flags);
       | ^  5196 | } // Add `RegExp.prototype` to the prototype chain
  5197 | 
  5198 | 

buildOpeningDelimiterRegExp
src/github.com/redventures/gkw/web/node_modules/slack-hawk-down/dist/bundle.js:580

  577 |       d = b.openingWhitespace ? "(?<openingCapturedWhitespace>^|\\s*)" : "",
  578 |       e = b.allowCharacterPad ? "" : c,
  579 |       f = b.startAnchored ? "(?<=^|\\n)" : e;
> 580 |   return new _xregexp["default"]("".concat(f).concat(a).concat(d, "(?=\\S)"), "n");
      | ^  581 | },
  582 |     buildClosingDelimiterRegExp = function buildClosingDelimiterRegExp(a) {
  583 |   var b = 1 < arguments.length && arguments[1] !== void 0 ? arguments[1] : {},

./node_modules/slack-hawk-down/dist/bundle.js/</<[5]<
src/github.com/redventures/gkw/web/node_modules/slack-hawk-down/dist/bundle.js:604

  601 | exports.blockQuoteDelimiter = "&gt;&gt;&gt;";
  602 | var inlineQuoteDelimiter = "&gt;";
  603 | exports.inlineQuoteDelimiter = "&gt;";
> 604 | var blockCodeOpeningPattern = buildOpeningDelimiterRegExp(_xregexp["default"].escape(blockCodeDelimiter), {
      | ^  605 |   noQuotePad: !0,
  606 |   openingWhitespace: !0
  607 | });
```

**Comment by alechoey** [comment]
Thanks for your interest.

A friendly reminder that this is no longer the official repository that the package is published out of. You can find the new repo at [alechoey/slack-hawk-down](https://github.com/alechoey/slack-hawk-down).

You're right that the current versions are broken for Firefox and Safari, since they rely on lookbehind assertions, which haven't made it into those browsers. I would suggest downgrading to v0.4.1, though you'll miss out on some markdown behavior fixes. For 95% of Slack markdown you shouldn't notice the difference.

As of now, I'm not interested in backporting those RegExp changes.

Another friendly Github etiquette reminder is to provide as much information as possible to make debugging easier, such as: 
1. What version are you running?
2. package-lock.json or yarn.lock?
3. Smallest reproducing app? Codepen/JS Fiddle
4. Browser version in this case

Hope this addresses your issue.

**Comment by edwardofclt** [comment]
Fair point, thanks. I'll close this then.
